//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 02:02:01 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for company-updateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="company-updateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{}companyType"/>
 *         &lt;element name="company-profile-update" type="{}company-profile-updateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "company-updateType", propOrder = {
    "company",
    "companyProfileUpdate"
})
public class CompanyUpdateType {

    @XmlElement(required = true)
    protected CompanyType company;
    @XmlElement(name = "company-profile-update", required = true)
    protected CompanyProfileUpdateType companyProfileUpdate;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyType }
     *     
     */
    public CompanyType getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyType }
     *     
     */
    public void setCompany(CompanyType value) {
        this.company = value;
    }

    /**
     * Gets the value of the companyProfileUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyProfileUpdateType }
     *     
     */
    public CompanyProfileUpdateType getCompanyProfileUpdate() {
        return companyProfileUpdate;
    }

    /**
     * Sets the value of the companyProfileUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyProfileUpdateType }
     *     
     */
    public void setCompanyProfileUpdate(CompanyProfileUpdateType value) {
        this.companyProfileUpdate = value;
    }

}
