//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 06:48:16 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for company-person-updateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="company-person-updateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{}personType"/>
 *         &lt;element name="action" type="{}actionType"/>
 *         &lt;element name="old-position" type="{}old-positionType"/>
 *         &lt;element name="new-position" type="{}new-positionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "company-person-updateType", propOrder = {
    "person",
    "action",
    "oldPosition",
    "newPosition"
})
public class CompanyPersonUpdateType {

    @XmlElement(required = true)
    protected PersonType person;
    @XmlElement(required = true)
    protected ActionType action;
    @XmlElement(name = "old-position", required = true)
    protected OldPositionType oldPosition;
    @XmlElement(name = "new-position", required = true)
    protected NewPositionType newPosition;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the oldPosition property.
     * 
     * @return
     *     possible object is
     *     {@link OldPositionType }
     *     
     */
    public OldPositionType getOldPosition() {
        return oldPosition;
    }

    /**
     * Sets the value of the oldPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OldPositionType }
     *     
     */
    public void setOldPosition(OldPositionType value) {
        this.oldPosition = value;
    }

    /**
     * Gets the value of the newPosition property.
     * 
     * @return
     *     possible object is
     *     {@link NewPositionType }
     *     
     */
    public NewPositionType getNewPosition() {
        return newPosition;
    }

    /**
     * Sets the value of the newPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewPositionType }
     *     
     */
    public void setNewPosition(NewPositionType value) {
        this.newPosition = value;
    }

}
