//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 06:48:16 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for company-profile-updateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="company-profile-updateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="editor" type="{}editorType"/>
 *         &lt;element name="action" type="{}actionType"/>
 *         &lt;element name="profile-field" type="{}profile-fieldType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "company-profile-updateType", propOrder = {
    "editor",
    "action",
    "profileField"
})
public class CompanyProfileUpdateType {

    @XmlElement(required = true)
    protected EditorType editor;
    @XmlElement(required = true)
    protected ActionType action;
    @XmlElement(name = "profile-field", required = true)
    protected ProfileFieldType profileField;

    /**
     * Gets the value of the editor property.
     * 
     * @return
     *     possible object is
     *     {@link EditorType }
     *     
     */
    public EditorType getEditor() {
        return editor;
    }

    /**
     * Sets the value of the editor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditorType }
     *     
     */
    public void setEditor(EditorType value) {
        this.editor = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the profileField property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileFieldType }
     *     
     */
    public ProfileFieldType getProfileField() {
        return profileField;
    }

    /**
     * Sets the value of the profileField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileFieldType }
     *     
     */
    public void setProfileField(ProfileFieldType value) {
        this.profileField = value;
    }

}
