//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 06:48:16 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for item-contentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item-contentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invitation-request" type="{}invitation-requestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item-contentType", propOrder = {
    "invitationRequest"
})
public class ItemContentType {

    @XmlElement(name = "invitation-request", required = true)
    protected InvitationRequestType invitationRequest;

    /**
     * Gets the value of the invitationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InvitationRequestType }
     *     
     */
    public InvitationRequestType getInvitationRequest() {
        return invitationRequest;
    }

    /**
     * Sets the value of the invitationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvitationRequestType }
     *     
     */
    public void setInvitationRequest(InvitationRequestType value) {
        this.invitationRequest = value;
    }

}
