//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 06:48:16 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JobSearch_QNAME = new QName("", "job-search");
    private final static QName _Person_QNAME = new QName("", "person");
    private final static QName _Updates_QNAME = new QName("", "updates");
    private final static QName _PeopleSearch_QNAME = new QName("", "people-search");
    private final static QName _Error_QNAME = new QName("", "error");
    private final static QName _JobBookmark_QNAME = new QName("", "job-bookmark");
    private final static QName _CompanySearch_QNAME = new QName("", "company-search");
    private final static QName _IsLiked_QNAME = new QName("", "is-liked");
    private final static QName _JobSuggestions_QNAME = new QName("", "job-suggestions");
    private final static QName _Share_QNAME = new QName("", "share");
    private final static QName _MailboxItem_QNAME = new QName("", "mailbox-item");
    private final static QName _Company_QNAME = new QName("", "company");
    private final static QName _JobBookmarks_QNAME = new QName("", "job-bookmarks");
    private final static QName _Connections_QNAME = new QName("", "connections");
    private final static QName _UpdateComment_QNAME = new QName("", "update-comment");
    private final static QName _Products_QNAME = new QName("", "products");
    private final static QName _Activity_QNAME = new QName("", "activity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BucketType }
     * 
     */
    public BucketType createBucketType() {
        return new BucketType();
    }

    /**
     * Create an instance of {@link RecommendationsGivenType }
     * 
     */
    public RecommendationsGivenType createRecommendationsGivenType() {
        return new RecommendationsGivenType();
    }

    /**
     * Create an instance of {@link RecommendationType }
     * 
     */
    public RecommendationType createRecommendationType() {
        return new RecommendationType();
    }

    /**
     * Create an instance of {@link JobPosterType }
     * 
     */
    public JobPosterType createJobPosterType() {
        return new JobPosterType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link JobFunctionType }
     * 
     */
    public JobFunctionType createJobFunctionType() {
        return new JobFunctionType();
    }

    /**
     * Create an instance of {@link CompanySearchType }
     * 
     */
    public CompanySearchType createCompanySearchType() {
        return new CompanySearchType();
    }

    /**
     * Create an instance of {@link RecommenderType }
     * 
     */
    public RecommenderType createRecommenderType() {
        return new RecommenderType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link RecommendationTypeType }
     * 
     */
    public RecommendationTypeType createRecommendationTypeType() {
        return new RecommendationTypeType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link InvitationRequestType }
     * 
     */
    public InvitationRequestType createInvitationRequestType() {
        return new InvitationRequestType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link PostingDateType }
     * 
     */
    public PostingDateType createPostingDateType() {
        return new PostingDateType();
    }

    /**
     * Create an instance of {@link UpdatedFieldsType }
     * 
     */
    public UpdatedFieldsType createUpdatedFieldsType() {
        return new UpdatedFieldsType();
    }

    /**
     * Create an instance of {@link UpdateActionType }
     * 
     */
    public UpdateActionType createUpdateActionType() {
        return new UpdateActionType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link UpdatesType }
     * 
     */
    public UpdatesType createUpdatesType() {
        return new UpdatesType();
    }

    /**
     * Create an instance of {@link CompanyJobUpdateType }
     * 
     */
    public CompanyJobUpdateType createCompanyJobUpdateType() {
        return new CompanyJobUpdateType();
    }

    /**
     * Create an instance of {@link LikesType }
     * 
     */
    public LikesType createLikesType() {
        return new LikesType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link AnswerType }
     * 
     */
    public AnswerType createAnswerType() {
        return new AnswerType();
    }

    /**
     * Create an instance of {@link RecipientsType }
     * 
     */
    public RecipientsType createRecipientsType() {
        return new RecipientsType();
    }

    /**
     * Create an instance of {@link BucketsType }
     * 
     */
    public BucketsType createBucketsType() {
        return new BucketsType();
    }

    /**
     * Create an instance of {@link IndustriesType }
     * 
     */
    public IndustriesType createIndustriesType() {
        return new IndustriesType();
    }

    /**
     * Create an instance of {@link CurrentShareType }
     * 
     */
    public CurrentShareType createCurrentShareType() {
        return new CurrentShareType();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link QuestionCategoriesType }
     * 
     */
    public QuestionCategoriesType createQuestionCategoriesType() {
        return new QuestionCategoriesType();
    }

    /**
     * Create an instance of {@link MemberUrlResourceTypeType }
     * 
     */
    public MemberUrlResourceTypeType createMemberUrlResourceTypeType() {
        return new MemberUrlResourceTypeType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link JobSearchType }
     * 
     */
    public JobSearchType createJobSearchType() {
        return new JobSearchType();
    }

    /**
     * Create an instance of {@link ExpirationDateType }
     * 
     */
    public ExpirationDateType createExpirationDateType() {
        return new ExpirationDateType();
    }

    /**
     * Create an instance of {@link ProfileFieldType }
     * 
     */
    public ProfileFieldType createProfileFieldType() {
        return new ProfileFieldType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ActivityType }
     * 
     */
    public ActivityType createActivityType() {
        return new ActivityType();
    }

    /**
     * Create an instance of {@link UpdateType }
     * 
     */
    public UpdateType createUpdateType() {
        return new UpdateType();
    }

    /**
     * Create an instance of {@link UpdateContentType }
     * 
     */
    public UpdateContentType createUpdateContentType() {
        return new UpdateContentType();
    }

    /**
     * Create an instance of {@link CompaniesType }
     * 
     */
    public CompaniesType createCompaniesType() {
        return new CompaniesType();
    }

    /**
     * Create an instance of {@link SiteGroupRequestType }
     * 
     */
    public SiteGroupRequestType createSiteGroupRequestType() {
        return new SiteGroupRequestType();
    }

    /**
     * Create an instance of {@link QuestionCategoryType }
     * 
     */
    public QuestionCategoryType createQuestionCategoryType() {
        return new QuestionCategoryType();
    }

    /**
     * Create an instance of {@link SpecialtiesType }
     * 
     */
    public SpecialtiesType createSpecialtiesType() {
        return new SpecialtiesType();
    }

    /**
     * Create an instance of {@link RelationToViewerType }
     * 
     */
    public RelationToViewerType createRelationToViewerType() {
        return new RelationToViewerType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link FacetType }
     * 
     */
    public FacetType createFacetType() {
        return new FacetType();
    }

    /**
     * Create an instance of {@link JobSuggestionsType }
     * 
     */
    public JobSuggestionsType createJobSuggestionsType() {
        return new JobSuggestionsType();
    }

    /**
     * Create an instance of {@link PeopleType }
     * 
     */
    public PeopleType createPeopleType() {
        return new PeopleType();
    }

    /**
     * Create an instance of {@link LikeType }
     * 
     */
    public LikeType createLikeType() {
        return new LikeType();
    }

    /**
     * Create an instance of {@link ProductCategoryType }
     * 
     */
    public ProductCategoryType createProductCategoryType() {
        return new ProductCategoryType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link RecommendationsType }
     * 
     */
    public RecommendationsType createRecommendationsType() {
        return new RecommendationsType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link MemberGroupType }
     * 
     */
    public MemberGroupType createMemberGroupType() {
        return new MemberGroupType();
    }

    /**
     * Create an instance of {@link ShareType }
     * 
     */
    public ShareType createShareType() {
        return new ShareType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link HeadersType }
     * 
     */
    public HeadersType createHeadersType() {
        return new HeadersType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link TwitterAccountType }
     * 
     */
    public TwitterAccountType createTwitterAccountType() {
        return new TwitterAccountType();
    }

    /**
     * Create an instance of {@link OldPositionType }
     * 
     */
    public OldPositionType createOldPositionType() {
        return new OldPositionType();
    }

    /**
     * Create an instance of {@link SalesPersonsType }
     * 
     */
    public SalesPersonsType createSalesPersonsType() {
        return new SalesPersonsType();
    }

    /**
     * Create an instance of {@link QuestionType }
     * 
     */
    public QuestionType createQuestionType() {
        return new QuestionType();
    }

    /**
     * Create an instance of {@link CompanyPersonUpdateType }
     * 
     */
    public CompanyPersonUpdateType createCompanyPersonUpdateType() {
        return new CompanyPersonUpdateType();
    }

    /**
     * Create an instance of {@link LocationType.ContactInfo }
     * 
     */
    public LocationType.ContactInfo createLocationTypeContactInfo() {
        return new LocationType.ContactInfo();
    }

    /**
     * Create an instance of {@link UpdateCommentType }
     * 
     */
    public UpdateCommentType createUpdateCommentType() {
        return new UpdateCommentType();
    }

    /**
     * Create an instance of {@link OriginalUpdateType }
     * 
     */
    public OriginalUpdateType createOriginalUpdateType() {
        return new OriginalUpdateType();
    }

    /**
     * Create an instance of {@link ThreeCurrentPositionsType }
     * 
     */
    public ThreeCurrentPositionsType createThreeCurrentPositionsType() {
        return new ThreeCurrentPositionsType();
    }

    /**
     * Create an instance of {@link JobFunctionsType }
     * 
     */
    public JobFunctionsType createJobFunctionsType() {
        return new JobFunctionsType();
    }

    /**
     * Create an instance of {@link RecipientType }
     * 
     */
    public RecipientType createRecipientType() {
        return new RecipientType();
    }

    /**
     * Create an instance of {@link MemberUrlResourcesType }
     * 
     */
    public MemberUrlResourcesType createMemberUrlResourcesType() {
        return new MemberUrlResourcesType();
    }

    /**
     * Create an instance of {@link MemberGroupsType }
     * 
     */
    public MemberGroupsType createMemberGroupsType() {
        return new MemberGroupsType();
    }

    /**
     * Create an instance of {@link SiteStandardProfileRequestType }
     * 
     */
    public SiteStandardProfileRequestType createSiteStandardProfileRequestType() {
        return new SiteStandardProfileRequestType();
    }

    /**
     * Create an instance of {@link EditorType }
     * 
     */
    public EditorType createEditorType() {
        return new EditorType();
    }

    /**
     * Create an instance of {@link RecommendeeType }
     * 
     */
    public RecommendeeType createRecommendeeType() {
        return new RecommendeeType();
    }

    /**
     * Create an instance of {@link ApiStandardProfileRequestType }
     * 
     */
    public ApiStandardProfileRequestType createApiStandardProfileRequestType() {
        return new ApiStandardProfileRequestType();
    }

    /**
     * Create an instance of {@link UpdateFieldType }
     * 
     */
    public UpdateFieldType createUpdateFieldType() {
        return new UpdateFieldType();
    }

    /**
     * Create an instance of {@link MemberUrlResourceType }
     * 
     */
    public MemberUrlResourceType createMemberUrlResourceType() {
        return new MemberUrlResourceType();
    }

    /**
     * Create an instance of {@link TwitterAccountsType }
     * 
     */
    public TwitterAccountsType createTwitterAccountsType() {
        return new TwitterAccountsType();
    }

    /**
     * Create an instance of {@link CompanyUpdateType }
     * 
     */
    public CompanyUpdateType createCompanyUpdateType() {
        return new CompanyUpdateType();
    }

    /**
     * Create an instance of {@link JobBookmarksType }
     * 
     */
    public JobBookmarksType createJobBookmarksType() {
        return new JobBookmarksType();
    }

    /**
     * Create an instance of {@link UpdateCommentsType }
     * 
     */
    public UpdateCommentsType createUpdateCommentsType() {
        return new UpdateCommentsType();
    }

    /**
     * Create an instance of {@link PeopleSearchType }
     * 
     */
    public PeopleSearchType createPeopleSearchType() {
        return new PeopleSearchType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link MailboxItemType }
     * 
     */
    public MailboxItemType createMailboxItemType() {
        return new MailboxItemType();
    }

    /**
     * Create an instance of {@link StartDateType }
     * 
     */
    public StartDateType createStartDateType() {
        return new StartDateType();
    }

    /**
     * Create an instance of {@link CompanyProfileUpdateType }
     * 
     */
    public CompanyProfileUpdateType createCompanyProfileUpdateType() {
        return new CompanyProfileUpdateType();
    }

    /**
     * Create an instance of {@link NewPositionType }
     * 
     */
    public NewPositionType createNewPositionType() {
        return new NewPositionType();
    }

    /**
     * Create an instance of {@link EndDateType }
     * 
     */
    public EndDateType createEndDateType() {
        return new EndDateType();
    }

    /**
     * Create an instance of {@link PositionsType }
     * 
     */
    public PositionsType createPositionsType() {
        return new PositionsType();
    }

    /**
     * Create an instance of {@link FacetsType }
     * 
     */
    public FacetsType createFacetsType() {
        return new FacetsType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link AnswersType }
     * 
     */
    public AnswersType createAnswersType() {
        return new AnswersType();
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link PersonActivitiesType }
     * 
     */
    public PersonActivitiesType createPersonActivitiesType() {
        return new PersonActivitiesType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AuthorizationType }
     * 
     */
    public AuthorizationType createAuthorizationType() {
        return new AuthorizationType();
    }

    /**
     * Create an instance of {@link ExperienceLevelType }
     * 
     */
    public ExperienceLevelType createExperienceLevelType() {
        return new ExperienceLevelType();
    }

    /**
     * Create an instance of {@link IndustryType }
     * 
     */
    public IndustryType createIndustryType() {
        return new IndustryType();
    }

    /**
     * Create an instance of {@link JobTypeType }
     * 
     */
    public JobTypeType createJobTypeType() {
        return new JobTypeType();
    }

    /**
     * Create an instance of {@link EmployeeCountRangeType }
     * 
     */
    public EmployeeCountRangeType createEmployeeCountRangeType() {
        return new EmployeeCountRangeType();
    }

    /**
     * Create an instance of {@link CompanyTypeType }
     * 
     */
    public CompanyTypeType createCompanyTypeType() {
        return new CompanyTypeType();
    }

    /**
     * Create an instance of {@link ItemContentType }
     * 
     */
    public ItemContentType createItemContentType() {
        return new ItemContentType();
    }

    /**
     * Create an instance of {@link JobBookmarkType }
     * 
     */
    public JobBookmarkType createJobBookmarkType() {
        return new JobBookmarkType();
    }

    /**
     * Create an instance of {@link EducationsType }
     * 
     */
    public EducationsType createEducationsType() {
        return new EducationsType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link ConnectionsType }
     * 
     */
    public ConnectionsType createConnectionsType() {
        return new ConnectionsType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link VisibilityType }
     * 
     */
    public VisibilityType createVisibilityType() {
        return new VisibilityType();
    }

    /**
     * Create an instance of {@link SiteJobRequestType }
     * 
     */
    public SiteJobRequestType createSiteJobRequestType() {
        return new SiteJobRequestType();
    }

    /**
     * Create an instance of {@link JobsType }
     * 
     */
    public JobsType createJobsType() {
        return new JobsType();
    }

    /**
     * Create an instance of {@link HttpHeaderType }
     * 
     */
    public HttpHeaderType createHttpHeaderType() {
        return new HttpHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobSearchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "job-search")
    public JAXBElement<JobSearchType> createJobSearch(JobSearchType value) {
        return new JAXBElement<JobSearchType>(_JobSearch_QNAME, JobSearchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "updates")
    public JAXBElement<UpdatesType> createUpdates(UpdatesType value) {
        return new JAXBElement<UpdatesType>(_Updates_QNAME, UpdatesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeopleSearchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "people-search")
    public JAXBElement<PeopleSearchType> createPeopleSearch(PeopleSearchType value) {
        return new JAXBElement<PeopleSearchType>(_PeopleSearch_QNAME, PeopleSearchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "error")
    public JAXBElement<ErrorType> createError(ErrorType value) {
        return new JAXBElement<ErrorType>(_Error_QNAME, ErrorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobBookmarkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "job-bookmark")
    public JAXBElement<JobBookmarkType> createJobBookmark(JobBookmarkType value) {
        return new JAXBElement<JobBookmarkType>(_JobBookmark_QNAME, JobBookmarkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompanySearchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company-search")
    public JAXBElement<CompanySearchType> createCompanySearch(CompanySearchType value) {
        return new JAXBElement<CompanySearchType>(_CompanySearch_QNAME, CompanySearchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is-liked")
    public JAXBElement<String> createIsLiked(String value) {
        return new JAXBElement<String>(_IsLiked_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobSuggestionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "job-suggestions")
    public JAXBElement<JobSuggestionsType> createJobSuggestions(JobSuggestionsType value) {
        return new JAXBElement<JobSuggestionsType>(_JobSuggestions_QNAME, JobSuggestionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "share")
    public JAXBElement<ShareType> createShare(ShareType value) {
        return new JAXBElement<ShareType>(_Share_QNAME, ShareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MailboxItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mailbox-item")
    public JAXBElement<MailboxItemType> createMailboxItem(MailboxItemType value) {
        return new JAXBElement<MailboxItemType>(_MailboxItem_QNAME, MailboxItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompanyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company")
    public JAXBElement<CompanyType> createCompany(CompanyType value) {
        return new JAXBElement<CompanyType>(_Company_QNAME, CompanyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobBookmarksType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "job-bookmarks")
    public JAXBElement<JobBookmarksType> createJobBookmarks(JobBookmarksType value) {
        return new JAXBElement<JobBookmarksType>(_JobBookmarks_QNAME, JobBookmarksType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connections")
    public JAXBElement<ConnectionsType> createConnections(ConnectionsType value) {
        return new JAXBElement<ConnectionsType>(_Connections_QNAME, ConnectionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCommentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "update-comment")
    public JAXBElement<UpdateCommentType> createUpdateComment(UpdateCommentType value) {
        return new JAXBElement<UpdateCommentType>(_UpdateComment_QNAME, UpdateCommentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "products")
    public JAXBElement<ProductsType> createProducts(ProductsType value) {
        return new JAXBElement<ProductsType>(_Products_QNAME, ProductsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "activity")
    public JAXBElement<ActivityType> createActivity(ActivityType value) {
        return new JAXBElement<ActivityType>(_Activity_QNAME, ActivityType.class, null, value);
    }

}
