//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.10 at 12:05:40 AM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Person_QNAME = new QName("", "person");
    private final static QName _PeopleSearch_QNAME = new QName("", "people-search");
    private final static QName _Updates_QNAME = new QName("", "updates");
    private final static QName _Error_QNAME = new QName("", "error");
    private final static QName _Connections_QNAME = new QName("", "connections");
    private final static QName _CompanySearch_QNAME = new QName("", "company-search");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StartDateType }
     * 
     */
    public StartDateType createStartDateType() {
        return new StartDateType();
    }

    /**
     * Create an instance of {@link UpdateContentType }
     * 
     */
    public UpdateContentType createUpdateContentType() {
        return new UpdateContentType();
    }

    /**
     * Create an instance of {@link LikeType }
     * 
     */
    public LikeType createLikeType() {
        return new LikeType();
    }

    /**
     * Create an instance of {@link EmployeeCountRangeType }
     * 
     */
    public EmployeeCountRangeType createEmployeeCountRangeType() {
        return new EmployeeCountRangeType();
    }

    /**
     * Create an instance of {@link IndustryType }
     * 
     */
    public IndustryType createIndustryType() {
        return new IndustryType();
    }

    /**
     * Create an instance of {@link UpdatesType }
     * 
     */
    public UpdatesType createUpdatesType() {
        return new UpdatesType();
    }

    /**
     * Create an instance of {@link UpdatedFieldsType }
     * 
     */
    public UpdatedFieldsType createUpdatedFieldsType() {
        return new UpdatedFieldsType();
    }

    /**
     * Create an instance of {@link MemberUrlResourceTypeType }
     * 
     */
    public MemberUrlResourceTypeType createMemberUrlResourceTypeType() {
        return new MemberUrlResourceTypeType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link CompanySearchType }
     * 
     */
    public CompanySearchType createCompanySearchType() {
        return new CompanySearchType();
    }

    /**
     * Create an instance of {@link ApiStandardProfileRequestType }
     * 
     */
    public ApiStandardProfileRequestType createApiStandardProfileRequestType() {
        return new ApiStandardProfileRequestType();
    }

    /**
     * Create an instance of {@link EducationsType }
     * 
     */
    public EducationsType createEducationsType() {
        return new EducationsType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ConnectionsType }
     * 
     */
    public ConnectionsType createConnectionsType() {
        return new ConnectionsType();
    }

    /**
     * Create an instance of {@link LikesType }
     * 
     */
    public LikesType createLikesType() {
        return new LikesType();
    }

    /**
     * Create an instance of {@link UpdateFieldType }
     * 
     */
    public UpdateFieldType createUpdateFieldType() {
        return new UpdateFieldType();
    }

    /**
     * Create an instance of {@link HttpHeaderType }
     * 
     */
    public HttpHeaderType createHttpHeaderType() {
        return new HttpHeaderType();
    }

    /**
     * Create an instance of {@link UpdateCommentsType }
     * 
     */
    public UpdateCommentsType createUpdateCommentsType() {
        return new UpdateCommentsType();
    }

    /**
     * Create an instance of {@link MemberUrlResourcesType }
     * 
     */
    public MemberUrlResourcesType createMemberUrlResourcesType() {
        return new MemberUrlResourcesType();
    }

    /**
     * Create an instance of {@link HeadersType }
     * 
     */
    public HeadersType createHeadersType() {
        return new HeadersType();
    }

    /**
     * Create an instance of {@link MemberUrlResourceType }
     * 
     */
    public MemberUrlResourceType createMemberUrlResourceType() {
        return new MemberUrlResourceType();
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link LocationType.ContactInfo }
     * 
     */
    public LocationType.ContactInfo createLocationTypeContactInfo() {
        return new LocationType.ContactInfo();
    }

    /**
     * Create an instance of {@link CompaniesType }
     * 
     */
    public CompaniesType createCompaniesType() {
        return new CompaniesType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link UpdateType }
     * 
     */
    public UpdateType createUpdateType() {
        return new UpdateType();
    }

    /**
     * Create an instance of {@link PeopleSearchType }
     * 
     */
    public PeopleSearchType createPeopleSearchType() {
        return new PeopleSearchType();
    }

    /**
     * Create an instance of {@link PositionsType }
     * 
     */
    public PositionsType createPositionsType() {
        return new PositionsType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link SiteStandardProfileRequestType }
     * 
     */
    public SiteStandardProfileRequestType createSiteStandardProfileRequestType() {
        return new SiteStandardProfileRequestType();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link MemberGroupsType }
     * 
     */
    public MemberGroupsType createMemberGroupsType() {
        return new MemberGroupsType();
    }

    /**
     * Create an instance of {@link PeopleType }
     * 
     */
    public PeopleType createPeopleType() {
        return new PeopleType();
    }

    /**
     * Create an instance of {@link ThreeCurrentPositionsType }
     * 
     */
    public ThreeCurrentPositionsType createThreeCurrentPositionsType() {
        return new ThreeCurrentPositionsType();
    }

    /**
     * Create an instance of {@link SiteGroupRequestType }
     * 
     */
    public SiteGroupRequestType createSiteGroupRequestType() {
        return new SiteGroupRequestType();
    }

    /**
     * Create an instance of {@link SpecialtiesType }
     * 
     */
    public SpecialtiesType createSpecialtiesType() {
        return new SpecialtiesType();
    }

    /**
     * Create an instance of {@link EndDateType }
     * 
     */
    public EndDateType createEndDateType() {
        return new EndDateType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link MemberGroupType }
     * 
     */
    public MemberGroupType createMemberGroupType() {
        return new MemberGroupType();
    }

    /**
     * Create an instance of {@link RelationToViewerType }
     * 
     */
    public RelationToViewerType createRelationToViewerType() {
        return new RelationToViewerType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link IndustriesType }
     * 
     */
    public IndustriesType createIndustriesType() {
        return new IndustriesType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeopleSearchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "people-search")
    public JAXBElement<PeopleSearchType> createPeopleSearch(PeopleSearchType value) {
        return new JAXBElement<PeopleSearchType>(_PeopleSearch_QNAME, PeopleSearchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "updates")
    public JAXBElement<UpdatesType> createUpdates(UpdatesType value) {
        return new JAXBElement<UpdatesType>(_Updates_QNAME, UpdatesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "error")
    public JAXBElement<ErrorType> createError(ErrorType value) {
        return new JAXBElement<ErrorType>(_Error_QNAME, ErrorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "connections")
    public JAXBElement<ConnectionsType> createConnections(ConnectionsType value) {
        return new JAXBElement<ConnectionsType>(_Connections_QNAME, ConnectionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompanySearchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company-search")
    public JAXBElement<CompanySearchType> createCompanySearch(CompanySearchType value) {
        return new JAXBElement<CompanySearchType>(_CompanySearch_QNAME, CompanySearchType.class, null, value);
    }

}
