//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.10 at 12:05:40 AM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for personType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="api-standard-profile-request" type="{}api-standard-profile-requestType"/>
 *         &lt;element name="site-standard-profile-request" type="{}site-standard-profile-requestType"/>
 *         &lt;element name="location" type="{}locationType"/>
 *         &lt;element name="industry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="relation-to-viewer" type="{}relation-to-viewerType"/>
 *         &lt;element name="num-connections">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="positions" type="{}positionsType"/>
 *         &lt;element name="educations" type="{}educationsType"/>
 *         &lt;element name="three-current-positions" type="{}three-current-positionsType"/>
 *         &lt;element name="auth-token">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="connections" type="{}connectionsType"/>
 *         &lt;element name="member-url-resources" type="{}member-url-resourcesType"/>
 *         &lt;element name="member-groups" type="{}member-groupsType"/>
 *         &lt;element name="current-status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personType", propOrder = {
    "id",
    "firstName",
    "lastName",
    "headline",
    "pictureUrl",
    "apiStandardProfileRequest",
    "siteStandardProfileRequest",
    "location",
    "industry",
    "distance",
    "relationToViewer",
    "numConnections",
    "positions",
    "educations",
    "threeCurrentPositions",
    "authToken",
    "connections",
    "memberUrlResources",
    "memberGroups",
    "currentStatus"
})
public class PersonType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "first-name", required = true)
    protected String firstName;
    @XmlElement(name = "last-name", required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String headline;
    @XmlElement(name = "picture-url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String pictureUrl;
    @XmlElement(name = "api-standard-profile-request", required = true)
    protected ApiStandardProfileRequestType apiStandardProfileRequest;
    @XmlElement(name = "site-standard-profile-request", required = true)
    protected SiteStandardProfileRequestType siteStandardProfileRequest;
    @XmlElement(required = true)
    protected LocationType location;
    @XmlElement(required = true)
    protected String industry;
    protected byte distance;
    @XmlElement(name = "relation-to-viewer", required = true)
    protected RelationToViewerType relationToViewer;
    @XmlElement(name = "num-connections")
    protected short numConnections;
    @XmlElement(required = true)
    protected PositionsType positions;
    @XmlElement(required = true)
    protected EducationsType educations;
    @XmlElement(name = "three-current-positions", required = true)
    protected ThreeCurrentPositionsType threeCurrentPositions;
    @XmlElement(name = "auth-token", required = true)
    protected String authToken;
    @XmlElement(required = true)
    protected ConnectionsType connections;
    @XmlElement(name = "member-url-resources", required = true)
    protected MemberUrlResourcesType memberUrlResources;
    @XmlElement(name = "member-groups", required = true)
    protected MemberGroupsType memberGroups;
    @XmlElement(name = "current-status", required = true)
    protected String currentStatus;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the headline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadline() {
        return headline;
    }

    /**
     * Sets the value of the headline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadline(String value) {
        this.headline = value;
    }

    /**
     * Gets the value of the pictureUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * Sets the value of the pictureUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureUrl(String value) {
        this.pictureUrl = value;
    }

    /**
     * Gets the value of the apiStandardProfileRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ApiStandardProfileRequestType }
     *     
     */
    public ApiStandardProfileRequestType getApiStandardProfileRequest() {
        return apiStandardProfileRequest;
    }

    /**
     * Sets the value of the apiStandardProfileRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApiStandardProfileRequestType }
     *     
     */
    public void setApiStandardProfileRequest(ApiStandardProfileRequestType value) {
        this.apiStandardProfileRequest = value;
    }

    /**
     * Gets the value of the siteStandardProfileRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SiteStandardProfileRequestType }
     *     
     */
    public SiteStandardProfileRequestType getSiteStandardProfileRequest() {
        return siteStandardProfileRequest;
    }

    /**
     * Sets the value of the siteStandardProfileRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteStandardProfileRequestType }
     *     
     */
    public void setSiteStandardProfileRequest(SiteStandardProfileRequestType value) {
        this.siteStandardProfileRequest = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the industry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * Sets the value of the industry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustry(String value) {
        this.industry = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public byte getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(byte value) {
        this.distance = value;
    }

    /**
     * Gets the value of the relationToViewer property.
     * 
     * @return
     *     possible object is
     *     {@link RelationToViewerType }
     *     
     */
    public RelationToViewerType getRelationToViewer() {
        return relationToViewer;
    }

    /**
     * Sets the value of the relationToViewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationToViewerType }
     *     
     */
    public void setRelationToViewer(RelationToViewerType value) {
        this.relationToViewer = value;
    }

    /**
     * Gets the value of the numConnections property.
     * 
     */
    public short getNumConnections() {
        return numConnections;
    }

    /**
     * Sets the value of the numConnections property.
     * 
     */
    public void setNumConnections(short value) {
        this.numConnections = value;
    }

    /**
     * Gets the value of the positions property.
     * 
     * @return
     *     possible object is
     *     {@link PositionsType }
     *     
     */
    public PositionsType getPositions() {
        return positions;
    }

    /**
     * Sets the value of the positions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionsType }
     *     
     */
    public void setPositions(PositionsType value) {
        this.positions = value;
    }

    /**
     * Gets the value of the educations property.
     * 
     * @return
     *     possible object is
     *     {@link EducationsType }
     *     
     */
    public EducationsType getEducations() {
        return educations;
    }

    /**
     * Sets the value of the educations property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationsType }
     *     
     */
    public void setEducations(EducationsType value) {
        this.educations = value;
    }

    /**
     * Gets the value of the threeCurrentPositions property.
     * 
     * @return
     *     possible object is
     *     {@link ThreeCurrentPositionsType }
     *     
     */
    public ThreeCurrentPositionsType getThreeCurrentPositions() {
        return threeCurrentPositions;
    }

    /**
     * Sets the value of the threeCurrentPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThreeCurrentPositionsType }
     *     
     */
    public void setThreeCurrentPositions(ThreeCurrentPositionsType value) {
        this.threeCurrentPositions = value;
    }

    /**
     * Gets the value of the authToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * Sets the value of the authToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthToken(String value) {
        this.authToken = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionsType }
     *     
     */
    public ConnectionsType getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionsType }
     *     
     */
    public void setConnections(ConnectionsType value) {
        this.connections = value;
    }

    /**
     * Gets the value of the memberUrlResources property.
     * 
     * @return
     *     possible object is
     *     {@link MemberUrlResourcesType }
     *     
     */
    public MemberUrlResourcesType getMemberUrlResources() {
        return memberUrlResources;
    }

    /**
     * Sets the value of the memberUrlResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberUrlResourcesType }
     *     
     */
    public void setMemberUrlResources(MemberUrlResourcesType value) {
        this.memberUrlResources = value;
    }

    /**
     * Gets the value of the memberGroups property.
     * 
     * @return
     *     possible object is
     *     {@link MemberGroupsType }
     *     
     */
    public MemberGroupsType getMemberGroups() {
        return memberGroups;
    }

    /**
     * Sets the value of the memberGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberGroupsType }
     *     
     */
    public void setMemberGroups(MemberGroupsType value) {
        this.memberGroups = value;
    }

    /**
     * Gets the value of the currentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentStatus() {
        return currentStatus;
    }

    /**
     * Sets the value of the currentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentStatus(String value) {
        this.currentStatus = value;
    }

}
