//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 06:48:16 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{}typeType"/>
 *         &lt;element name="creation-timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="logo-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="features" type="{}featuresType"/>
 *         &lt;element name="sales-persons" type="{}sales-personsType"/>
 *         &lt;element name="num-recommendations" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="recommendations" type="{}recommendationsType"/>
 *         &lt;element name="product-category" type="{}product-categoryType"/>
 *         &lt;element name="website-url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="disclaimer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productType", propOrder = {
    "id",
    "name",
    "type",
    "creationTimestamp",
    "logoUrl",
    "description",
    "features",
    "salesPersons",
    "numRecommendations",
    "recommendations",
    "productCategory",
    "websiteUrl",
    "disclaimer"
})
public class ProductType {

    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected TypeType type;
    @XmlElement(name = "creation-timestamp")
    protected long creationTimestamp;
    @XmlElement(name = "logo-url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String logoUrl;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected FeaturesType features;
    @XmlElement(name = "sales-persons", required = true)
    protected SalesPersonsType salesPersons;
    @XmlElement(name = "num-recommendations")
    protected byte numRecommendations;
    @XmlElement(required = true)
    protected RecommendationsType recommendations;
    @XmlElement(name = "product-category", required = true)
    protected ProductCategoryType productCategory;
    @XmlElement(name = "website-url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String websiteUrl;
    @XmlElement(required = true)
    protected String disclaimer;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeType }
     *     
     */
    public TypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeType }
     *     
     */
    public void setType(TypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the creationTimestamp property.
     * 
     */
    public long getCreationTimestamp() {
        return creationTimestamp;
    }

    /**
     * Sets the value of the creationTimestamp property.
     * 
     */
    public void setCreationTimestamp(long value) {
        this.creationTimestamp = value;
    }

    /**
     * Gets the value of the logoUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * Sets the value of the logoUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoUrl(String value) {
        this.logoUrl = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesType }
     *     
     */
    public FeaturesType getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesType }
     *     
     */
    public void setFeatures(FeaturesType value) {
        this.features = value;
    }

    /**
     * Gets the value of the salesPersons property.
     * 
     * @return
     *     possible object is
     *     {@link SalesPersonsType }
     *     
     */
    public SalesPersonsType getSalesPersons() {
        return salesPersons;
    }

    /**
     * Sets the value of the salesPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesPersonsType }
     *     
     */
    public void setSalesPersons(SalesPersonsType value) {
        this.salesPersons = value;
    }

    /**
     * Gets the value of the numRecommendations property.
     * 
     */
    public byte getNumRecommendations() {
        return numRecommendations;
    }

    /**
     * Sets the value of the numRecommendations property.
     * 
     */
    public void setNumRecommendations(byte value) {
        this.numRecommendations = value;
    }

    /**
     * Gets the value of the recommendations property.
     * 
     * @return
     *     possible object is
     *     {@link RecommendationsType }
     *     
     */
    public RecommendationsType getRecommendations() {
        return recommendations;
    }

    /**
     * Sets the value of the recommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecommendationsType }
     *     
     */
    public void setRecommendations(RecommendationsType value) {
        this.recommendations = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategoryType }
     *     
     */
    public ProductCategoryType getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategoryType }
     *     
     */
    public void setProductCategory(ProductCategoryType value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the websiteUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * Sets the value of the websiteUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsiteUrl(String value) {
        this.websiteUrl = value;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimer() {
        return disclaimer;
    }

    /**
     * Sets the value of the disclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimer(String value) {
        this.disclaimer = value;
    }

}
