//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 02:02:01 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for twitter-accountsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="twitter-accountsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="twitter-account" type="{}twitter-accountType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "twitter-accountsType", propOrder = {
    "twitterAccount"
})
public class TwitterAccountsType {

    @XmlElement(name = "twitter-account", required = true)
    protected TwitterAccountType twitterAccount;
    @XmlAttribute
    protected Byte count;

    /**
     * Gets the value of the twitterAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TwitterAccountType }
     *     
     */
    public TwitterAccountType getTwitterAccount() {
        return twitterAccount;
    }

    /**
     * Sets the value of the twitterAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwitterAccountType }
     *     
     */
    public void setTwitterAccount(TwitterAccountType value) {
        this.twitterAccount = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCount(Byte value) {
        this.count = value;
    }

}
