//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 02:02:01 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for update-contentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="update-contentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{}personType" minOccurs="0"/>
 *         &lt;element name="update-action" type="{}update-actionType" minOccurs="0"/>
 *         &lt;element name="question" type="{}questionType" minOccurs="0"/>
 *         &lt;element name="job" type="{}jobType" minOccurs="0"/>
 *         &lt;element name="company-update" type="{}company-updateType" minOccurs="0"/>
 *         &lt;element name="company" type="{}companyType" minOccurs="0"/>
 *         &lt;element name="company-job-update" type="{}company-job-updateType" minOccurs="0"/>
 *         &lt;element name="company-person-update" type="{}company-person-updateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "update-contentType", propOrder = {
    "person",
    "updateAction",
    "question",
    "job",
    "companyUpdate",
    "company",
    "companyJobUpdate",
    "companyPersonUpdate"
})
public class UpdateContentType {

    protected PersonType person;
    @XmlElement(name = "update-action")
    protected UpdateActionType updateAction;
    protected QuestionType question;
    protected JobType job;
    @XmlElement(name = "company-update")
    protected CompanyUpdateType companyUpdate;
    protected CompanyType company;
    @XmlElement(name = "company-job-update")
    protected CompanyJobUpdateType companyJobUpdate;
    @XmlElement(name = "company-person-update")
    protected CompanyPersonUpdateType companyPersonUpdate;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the updateAction property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateActionType }
     *     
     */
    public UpdateActionType getUpdateAction() {
        return updateAction;
    }

    /**
     * Sets the value of the updateAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateActionType }
     *     
     */
    public void setUpdateAction(UpdateActionType value) {
        this.updateAction = value;
    }

    /**
     * Gets the value of the question property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionType }
     *     
     */
    public QuestionType getQuestion() {
        return question;
    }

    /**
     * Sets the value of the question property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionType }
     *     
     */
    public void setQuestion(QuestionType value) {
        this.question = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link JobType }
     *     
     */
    public JobType getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobType }
     *     
     */
    public void setJob(JobType value) {
        this.job = value;
    }

    /**
     * Gets the value of the companyUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyUpdateType }
     *     
     */
    public CompanyUpdateType getCompanyUpdate() {
        return companyUpdate;
    }

    /**
     * Sets the value of the companyUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyUpdateType }
     *     
     */
    public void setCompanyUpdate(CompanyUpdateType value) {
        this.companyUpdate = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyType }
     *     
     */
    public CompanyType getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyType }
     *     
     */
    public void setCompany(CompanyType value) {
        this.company = value;
    }

    /**
     * Gets the value of the companyJobUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyJobUpdateType }
     *     
     */
    public CompanyJobUpdateType getCompanyJobUpdate() {
        return companyJobUpdate;
    }

    /**
     * Sets the value of the companyJobUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyJobUpdateType }
     *     
     */
    public void setCompanyJobUpdate(CompanyJobUpdateType value) {
        this.companyJobUpdate = value;
    }

    /**
     * Gets the value of the companyPersonUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyPersonUpdateType }
     *     
     */
    public CompanyPersonUpdateType getCompanyPersonUpdate() {
        return companyPersonUpdate;
    }

    /**
     * Sets the value of the companyPersonUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyPersonUpdateType }
     *     
     */
    public void setCompanyPersonUpdate(CompanyPersonUpdateType value) {
        this.companyPersonUpdate = value;
    }

}
