//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 02:02:01 PM IST 
//


package org.bandhu.ext.linkedin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for update-actionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="update-actionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" type="{}actionType"/>
 *         &lt;element name="original-update" type="{}original-updateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "update-actionType", propOrder = {
    "action",
    "originalUpdate"
})
public class UpdateActionType {

    @XmlElement(required = true)
    protected ActionType action;
    @XmlElement(name = "original-update", required = true)
    protected OriginalUpdateType originalUpdate;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the originalUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalUpdateType }
     *     
     */
    public OriginalUpdateType getOriginalUpdate() {
        return originalUpdate;
    }

    /**
     * Sets the value of the originalUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalUpdateType }
     *     
     */
    public void setOriginalUpdate(OriginalUpdateType value) {
        this.originalUpdate = value;
    }

}
